feat: add food icon beside the Hunger Bar
Terasology/Hunger pull request #30
Opened 2021-10-13 13:09 UTC by mohamedation

add food icon indicator on the left of the hunger bar
![Screenshot from 2021-10-13 15-05-15](https://user-images.githubusercontent.com/11461094/137138856-415ddec2-d65d-42e1-b003-95df06bee9c3.png)

2021-10-15 16:56 UTC, jdrueckert requested changes
I feel like it helps associating the contents of this file with what you can see in-game if the elements are in the same "order", aka if the icon comes first and then the bar.

Further, I think we should make the horizontal placement of the bar relative to the icon. Thus, they'll always have the same offset even if you decide to move it further right or left by adjusting the icon's horizontal placement. I would recommend the following for the bar:
```
"position-left": {
    "target": "LEFT",
    "widget": "hungerIcon",
    "offset": 47
},
```

2021-10-15 16:56 UTC, jdrueckert commented on assets/ui/Hunger.ui
> +                        "offset": 80
nitpick: should be a tad higher
```suggestion
                        "offset": 81
```

2021-10-15 16:56 UTC, jdrueckert commented on assets/ui/Hunger.ui
> +                    "height": 15,
I think we can align the height with the thirst icon height here
```suggestion
                    "height": 18,
```

2021-10-16 20:02 UTC, mohamedation commented
As always, thank you for your assistance

2021-10-18 19:46 UTC, jdrueckert reviewed
Did you test this in-game?
I don't expect it to work because for positioning the `hungerIcon` widget you're referencing the `hungerIcon` widget. You'll need to position the icon like you currently position the bar and positioning the bar referencing the icon.

2021-10-19 10:31 UTC, mohamedation commented
@jdrueckert sorry for that. looks like i wasn't focusing right. i had tested the horizontal relative position in game (completely blanked that it  would be a good idea to do the same for the vertical position as well) but when i began to edit the files for the commit, i reversed the solution.

I have (hopefully now) corrected this, added also relative vertical position, and aligned everything again to the dot.
![hunger-thirst-alignment](https://user-images.githubusercontent.com/11461094/137892574-152a3448-28e9-4b90-886f-705e1cc94191.png)

2021-10-21 18:50 UTC, jdrueckert approved these changes

2021-10-21 18:50 UTC, merged

2021-10-21 18:55 UTC, jdrueckert commented
![](https://github.trello.services/images/mini-trello-icon.png) [Survival UI/UX improvements](https://trello.com/c/mDLqsnbp/186-survival-ui-ux-improvements)